### ISSUE TITLE
Transpile arrow function for es6 module

### ISSUE THREAD

**Issue by mtoso** [jonathantneal/document-promises#11]
Hello,

maybe I am completely wrong but my understanding is that the code should always already be transpiled even if you are exposing a ES6 bundle in "module". The only difference is that they use ES6 module syntax instead of commonjs function calls. So even if you are exporting an es6 module the library itself should expose a bundle transpiled to ES5 (for example the arrow functions in your code).

Thanks

**Comment by jonathantneal** [comment]
Node Package Modules are typically Node 4x compatible, as that is the oldest [Long Term Supported](https://github.com/nodejs/LTS) version.

I wrote this a long time ago, so I’m not certain; is it not Node 4x compatible?

**Comment by mtoso** [comment]
I am trying to use this lib in the browser so I have polyfill for Promise and EventListener but the code fail running in browser that are not supporting arrow function natively (like IE11). With Chrome everything works fine bc the native support of arrow function.

**Comment by jonathantneal** [comment]
If we’re using Node modules, we might need to expect a rollup/babel/browserify/your-choice step to ensure ES5 compatibility. That being said, this module _does_ compile it to ES5. See:

https://github.com/jonathantneal/document-promises/blob/master/package.json#L18

It may be that your project/build tool is purposefully using the module version. See how this is done:

https://github.com/jonathantneal/document-promises/blob/master/package.json#L10-L11

Does this make sense? I’m providing what you want under the `main` key. Your tooling may be requesting the `module` version anyway.

**Comment by mtoso** [comment]
Yes I am using webpack 3 and is using the `module` version as I expect to have the tree shaking functionality, but my point is that even if you export a ES6 module the code like arrow function should be transpiled.

I was reading this: https://github.com/webpack/webpack/issues/2902

**Comment by btd** [comment]
Another issue there, that you provide your own babel config. Which include module transpillation....

**Comment by jonathantneal** [comment]
This has been addressed in v4 🎉
