### ISSUE TITLE
Avoid triggering getters

### ISSUE THREAD

**Issue by jonathantneal** [jonathantneal/document-promises#5]
@WebReflection may have mentioned in [#4](https://github.com/jonathantneal/document-promises/issues/4#issuecomment-256127510) that I should avoid checking `!document.loaded`, as it may trigger getters. I’m wondering if I should instead use `!('loaded' in document)`, or what best practice I should follow.

**Comment by WebReflection** [comment]
considering one of your solutions there is to lazily assign on `get`, I think you answered your own question already ;-)

It's a trap either ways, but using `in` does not involve extra, most likely unnecessary, logic.

**Comment by jonathantneal** [comment]
Since feature detection is not part of a ponyfill, I’ll close this. Thanks for your assistance.
